### ISSUE TITLE
Setup feedback

### ISSUE THREAD

**Issue by matthova** [agoda-com/eslint-config-agoda#10]
I created a demo expo project using expo-cli and this repo's instructions.

Two things I noticed:
1. Even when using npx I still had to manually add the eslint package eslint
```
yarn add -D eslint
```
2. In my example app, no error is thrown when referencing an unknown variable. This is true from both VSCode's IDE and the command-line `yarn lint`
https://github.com/matthova/expots/blob/master/App.tsx#L22

Thanks for sharing your setup. Would love to figure out how to get this working :)

**Comment by matmalkowski** [comment]
@matthova I just noticed this issue, for some reason I must have missed the notification in Nov. 

It might be worth to mention `eslint ` in yarn add command maybe, I just assumed that since this is config that extends the default one, people installing it would already have eslint as dependency. But feel free to submit a PR for the Readme file.

Were you able to figure out the second issue you mention?
